---
description: 
pack: aws_gamelift
enabled: true
entry_point: run.py
name: delete_matchmaking_configuration
runner_type: python-script
parameters:
  action:
    default: delete_matchmaking_configuration
    immutable: true
    type: string
  cls:
    default: gamelift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Name:
    type: string
    description: "Unique identifier for a matchmaking configuration"
    required: true