---
description: 
pack: aws_gamelift
enabled: true
entry_point: run.py
name: describe_matchmaking_configurations
runner_type: python-script
parameters:
  action:
    default: describe_matchmaking_configurations
    immutable: true
    type: string
  cls:
    default: gamelift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Names:
    type: array
    description: "Unique identifier for a matchmaking configuration(s) to retrieve. To request all existing configurations, leave this parameter empty."
  RuleSetName:
    type: string
    description: "Unique identifier for a matchmaking rule set. Use this parameter to retrieve all matchmaking configurations that use this rule set."
  Limit:
    type: integer
    description: "Maximum number of results to return. Use this parameter with NextToken to get results as a set of sequential pages. This parameter is limited to 10."
  NextToken:
    type: string
    description: "Token that indicates the start of the next sequential page of results. Use the token that is returned with a previous call to this action. To start at the beginning of the result set, do not specify a value."