---
description: 
pack: aws_gamelift
enabled: true
entry_point: run.py
name: update_matchmaking_configuration
runner_type: python-script
parameters:
  action:
    default: update_matchmaking_configuration
    immutable: true
    type: string
  cls:
    default: gamelift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Name:
    type: string
    description: "Unique identifier for a matchmaking configuration to update."
    required: true
  Description:
    type: string
    description: "Descriptive label that is associated with matchmaking configuration."
  GameSessionQueueArns:
    type: array
    description: "Amazon Resource Name (ARN) that is assigned to a game session queue and uniquely identifies it. Format is arn:aws:gamelift:&lt;region&gt;::fleet/fleet-a1234567-b8c9-0d1e-2fa3-b45c6d7e8912. These queues are used when placing game sessions for matches that are created with this matchmaking configuration. Queues can be located in any region."
  RequestTimeoutSeconds:
    type: integer
    description: "Maximum duration, in seconds, that a matchmaking ticket can remain in process before timing out. Requests that time out can be resubmitted as needed."
  AcceptanceTimeoutSeconds:
    type: integer
    description: "Length of time (in seconds) to wait for players to accept a proposed match. If any player rejects the match or fails to accept before the timeout, the ticket continues to look for an acceptable match."
  AcceptanceRequired:
    type: boolean
    description: "Flag that determines whether or not a match that was created with this configuration must be accepted by the matched players. To require acceptance, set to TRUE."
  RuleSetName:
    type: string
    description: "Unique identifier for a matchmaking rule set to use with this configuration. A matchmaking configuration can only use rule sets that are defined in the same region."
  NotificationTarget:
    type: string
    description: "SNS topic ARN that is set up to receive matchmaking notifications. See  Setting up Notifications for Matchmaking for more information."
  AdditionalPlayerCount:
    type: integer
    description: "Number of player slots in a match to keep open for future players. For example, if the configuration's rule set specifies a match for a single 12-person team, and the additional player count is set to 2, only 10 players are selected for the match."
  CustomEventData:
    type: string
    description: "Information to attached to all events related to the matchmaking configuration. "
  GameProperties:
    type: array
    description: "Set of developer-defined properties for a game session, formatted as a set of type:value pairs. These properties are included in the GameSession object, which is passed to the game server with a request to start a new game session (see Start a Game Session). This information is added to the new GameSession object that is created for a successful match. "
  GameSessionData:
    type: string
    description: "Set of developer-defined game session properties, formatted as a single string value. This data is included in the GameSession object, which is passed to the game server with a request to start a new game session (see Start a Game Session). This information is added to the new GameSession object that is created for a successful match. "